--- # Outline Playbook and Installing the Project with Translation this contains multiple tasks executing the command
- hosts: local
  remote_user: ansible 
  become: yes
  become_method: sudo 
  gather_facts: no
  tasks: 
  - name: date/time stamp for when the playbook start
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: Install the tomcat webserver 
    yum: 
      name: tomcat
      state: latest
    notify: Restart Tomcat
  - name: start and verify the webservice is running
    service: name=tomcat state=restarted
  - name: verifying the runing
    command: systemctl status tomcat
    register: results
  - debug: var=result       
  - name: install client software - telnet 
    yum:
      name: telnet 
      state: latest
  - name: install client software - lynx
    yum: 
      name: lynx 
      state: latest
  - name: install client software - bluefish
    yum: 
      name: bluefish 
      state: latest
  - name: Logging the list of installed software
    command: yum list installed 
    register: list_details
  - debug: var=list_details   
  - name: Logging the time for setup
    command: /usr/bin/date
    register: finishResult
  - debug: var=finishResult
  handlers: 
  - name: Restart Tomcat
    service: name=tomcat state=restarted
