--- # UNTIL command for the testng 
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
   - name: Installing the Bluefish command
     yum: pkg=bluefish state=absent
   - name: Verify Service Status
     shell: sudo systemctl status postgres
     register: result
     until: result.stdout.find("active (running)") != -1 
     retries: 5
     delay: 5 
   - debug: var=result
     
