---
- name: Download alfresco community {{ alfresco_version }}
  get_url:
    url: http://dl.alfresco.com/release/community/{{ alfresco_version }}-build-{{ alfresco_build }}/alfresco-community-{{ alfresco_version_url }}.zip
    dest: /tmp/alfresco-community-{{ alfresco_version }}.zip
  register: alfresco_downloaded
  
- name: Extract alfresco
  command: unzip -o /tmp/alfresco-community-{{ alfresco_version }}.zip -d /tmp/alfresco/
  register: alfresco_extracted
  when: alfresco_downloaded is changed

- name: Install alfresco to tomcat
  shell: cp -rf /tmp/alfresco{{alfresco_archive_folder}}/web-server/* {{ alfresco_user_home }}/tomcat/
  when: alfresco_extracted is changed

- name: Install alfresco bin, licenses and readme
  shell: cp -rf /tmp/alfresco{{alfresco_archive_folder}}/bin /tmp/alfresco{{alfresco_archive_folder}}/licenses /tmp/alfresco{{alfresco_archive_folder}}/README.txt {{ alfresco_user_home }}/
  when: alfresco_extracted is changed

- name: Install alfresco amps for alfresco share (5.2)
  shell: cp -rf /tmp/alfresco{{alfresco_archive_folder}}/amps {{ alfresco_user_home }}/
  when: setup_shared_alfresco

- name: Cleanup alfresco unzipped
  file: path=/tmp/alfresco state=absent
  when: alfresco_extracted is changed

- name: Create alfresco alf_data directory
  file: path={{ alfresco_user_home }}/alf_data state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted is changed

- name: Create alfresco amp directory if not exists
  file: path={{ alfresco_user_home }}/amps state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted is changed

- name: Create alfresco amp_share directory
  file: path={{ alfresco_user_home }}/amps_share state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted is changed

- name: Create alfresco log directory
  file: path={{ alfresco_log_home }} state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted is changed

- name: Install libreoffice startup script
  copy: src=start_oo.sh dest={{ alfresco_user_home }}/bin/start_oo.sh owner={{ alfresco_user }} group={{ alfresco_group }} mode=0755
  when: alfresco_extracted is changed

- name: Install alfresco startup script
  template: src=alfresco.sh.j2 dest={{ alfresco_user_home }}/bin/alfresco.sh owner={{ alfresco_user }} group={{ alfresco_group }} mode=0755 backup=yes
  when: alfresco_extracted is changed

- name: Install alfresco init script
  template: src=alfresco.j2 dest=/etc/init.d/alfresco owner={{ alfresco_user }} group={{ alfresco_group }} mode=0755
  when: alfresco_extracted is changed

- name: Install alfresco global configuration
  template: src=alfresco-global.properties.j2 dest={{ alfresco_user_home }}/tomcat/shared/classes/alfresco-global.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644 backup=yes
  when: alfresco_extracted is changed

- name: Install alfresco logging configuration
  template: src=custom-log4j.properties.j2 dest={{ alfresco_user_home }}/tomcat/shared/classes/alfresco/extension/custom-log4j.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_extracted is changed

- name: Set alfresco file owner
  shell: chown -R {{ alfresco_user }}:{{ alfresco_group }} {{ alfresco_user_home }} && chown -R {{ alfresco_user }}:{{ alfresco_group }} {{ alfresco_user_home }}/tomcat/
  when: alfresco_extracted is changed
  
- include: azure-blob-storage.yml
  when: setup_azure_blob_storage

- name: Start alfresco server
  shell: /sbin/service alfresco start
  when: alfresco_extracted is changed
  
- name: Wait for alfresco war deploy
  wait_for: path=/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/web.xml
  when: alfresco_extracted is changed

- name: Remove old conf alfresco.xml and share.xml catalina for Tomcat8
  file:
    state: absent
    path: "{{ alfresco_user_home }}/tomcat/conf/Catalina/localhost/"
  when:
    - '{{ tomcat_version[0:1]|int}} > 7'
    - 'alfresco_extracted is changed'
  
- name: wait for alfresco log
  wait_for:
    path: '{{ alfresco_user_home }}/tomcat/logs/catalina.out'
    state: present

- name: wait for alfresco startup
  shell: 'grep "Server startup in" {{ alfresco_user_home }}/tomcat/logs/catalina.out'
  register: cmd_result
  retries: 1000
  delay: 5
  until: cmd_result is success

- name: clean previous logs
  file:
    state: absent
    path: '{{ alfresco_user_home }}/tomcat/logs/catalina.out'
  
- name: stop alfresco server
  shell: /sbin/service alfresco stop

- name: Apply amps Shared Alfresco
  shell: '/bin/sh {{ alfresco_user_home }}/bin/apply_amps.sh -force'
  when: setup_shared_alfresco
  
- name: start alfresco server
  shell: /sbin/service alfresco start

- name: wait for alfresco log
  wait_for:
    path: '{{ alfresco_user_home }}/tomcat/logs/catalina.out'
    state: present

- name: wait for alfresco startup
  shell: 'grep "Server startup in" {{ alfresco_user_home }}/tomcat/logs/catalina.out'
  register: cmd_result
  retries: 1000
  delay: 5
  until: cmd_result is success
