---
- name: Download mysql-java-connector
  get_url:
    url: http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
    dest: /home/ansible/downloads/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
  register: mysqlconnector_downloaded
  
- name: Extract mysql-java-connector {{ mysql_connector_version }}
  unarchive:
    src: /home/ansible/downloads/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
    dest: /home/ansible/downloads
    remote_src: yes
  register: mysqlconnector_extracted
  when: mysqlconnector_downloaded is changed

- name: Install mysql-java-connector
  shell: 'mv /home/ansible/downloads/mysql-connector-java-{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}-bin.jar {{ tomcat_dir }}/lib/ && chown {{ alfresco_user }}:{{ alfresco_group }} {{ tomcat_dir }}/lib/mysql-connector-java-{{ mysql_connector_version }}-bin.jar'
  when: mysqlconnector_extracted is changed

- name: Cleanup mysql-java-connector
  shell: 'rm -rf /tmp/mysql-connector-java-{{ mysql_connector_version }}'
  when: mysqlconnector_extracted is changed
