---
- name: Download mysql-java-connector
  get_url:
    url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.35/mysql-connector-java-5.1.35.jar
    dest: /home/ansible/downloads/mysql-connector-java-5.1.35.jar
  register: mysqlconnector_downloaded

- name: Moving Mysql Jar  
  command: mv /home/ansible/downloads/mysql-connector-java-5.1.35.jar /opt/ansible/tomcat/lib/
  when: mysqlconnector_downloaded

#- name: Extract mysql-java-connector {{ mysql_connector_version }}
#  unarchive:
 #   src: /home/ansible/downloads/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
 #  dest: /home/ansible/downloads
 #   remote_src: yes
 # register: mysqlconnector_extracted
 # when: mysqlconnector_downloaded is changed

- name: Changin Ownership
  file: dest=/opt/ansible/ owner=ansible group=ansible mode=u=rwX,g=rX,o=rX recurse=yes
  when: mysqlconnector_downloaded is changed

#- name: Cleanup mysql-java-connector
#  shell: 'rm -rf /'
#  when: mysqlconnector_extracted is changed
