---
#- name: Download solr community
#  get_url:
#    url: http://dl.alfresco.com/release/community/{{ alfresco_version }}-build-{{ alfresco_build }}/{{ solr_version_url }}.zip
#    dest: /tmp/{{ solr_version_url }}.zip
#  register: alfresco_solr_downloaded

- name: Move to Directory
  command: cd /opt/ansible/archive
  register: moved_path

- name: Download Solr community
  shell: 'wget https://download.alfresco.com/release/community/4.2.f-build-00012/alfresco-community-solr-4.2.f.zip'
  register: downloaded_community_solr
  when: moved_path is success

#- name: Extract alfresco solr
#  command: unzip -o /opt/ansible/archive/alfresco-community-solr-4.2.f.zip  -d /opt/ansible/alfresco-community-solr-4.2.f
#  register: alfresco_solr_extracted
#  when: alfresco_solr_downloaded is changed

- name: Extract Alfresco Solr
  unarchive: 
   src: /opt/ansible/archive/alfresco-community-solr-4.2.f.zip
   dest: /opt/ansible/archive/alfresco-community-solr-4.2.f
   remote_src: yes
  register: alfresco_solr_extracted
  when: downloaded_community_solr is changed

- name: Create alfresco-solr directory
  file: path={{ alfresco_user_home }}/solr state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_solr_extracted is changed

- name: Install alfresco-solr to tomcat
  shell: cp -rf /tmp/alfresco-solr/* {{ alfresco_user_home }}/solr/
  when: alfresco_solr_extracted is changed
  
- name: Rename solr.war
  shell: mv {{ alfresco_user_home }}/solr/*.war {{ alfresco_user_home }}/solr/{{solr_version}}.war 
  when:
    - 'solr_version != "solr4"'
    - 'alfresco_solr_extracted is changed'

- name: Copy the context.xml file to tomcat
  template: src=solr.xml.j2 dest={{ alfresco_user_home }}/tomcat/conf/Catalina/localhost/{{solr_version}}.xml owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_solr_extracted is changed
  
- name: Configure the solcores properties for workspace
  template: src=solrcore.properties.j2 dest={{ alfresco_user_home }}/solr/workspace-SpacesStore/conf/solrcore.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_solr_extracted is changed
    
- name: Configure the solcores properties for archive
  template: src=solrcore.properties-archives.j2 dest={{ alfresco_user_home }}/solr/archive-SpacesStore/conf/solrcore.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_solr_extracted is changed
  
- name: Configure the solr config xml (lock) for workspace
  template: src=solrconfig.xml.j2 dest={{ alfresco_user_home }}/solr/workspace-SpacesStore/conf/solrconfig.xml owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_solr_extracted is changed
    
- name: Configure the solr config xml (lock) for archive
  template: src=solrconfig.xml.j2 dest={{ alfresco_user_home }}/solr/archive-SpacesStore/conf/solrconfig.xml owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_solr_extracted is changed

- name: Cleanup alfresco-solr unzipped
  file: path=/tmp/alfresco-solr state=absent
  when: alfresco_solr_extracted is changed

- name: Set solr file permissions
  file: path={{ alfresco_user_home}}/solr owner={{ alfresco_user }} group={{ alfresco_group }} recurse=yes
  notify:
   - restart alfresco
  when: alfresco_solr_extracted is changed

- name: Wait for alfresco war deploy
  wait_for: path=/opt/alfresco/tomcat/webapps/{{ solr_version }}/WEB-INF/web.xml
  when: alfresco_solr_extracted is changed

- name: Relax security constraint for repo http comunication
  copy: src=webSolr.xml dest={{ alfresco_user_home }}/tomcat/webapps/{{ solr_version }}/WEB-INF/web.xml owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  notify:
   - restart alfresco
  when: alfresco_solr_extracted is changed
