--- #Playbook Notification and handling Example for localhost
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: installing nginx web server
    yum: 
      name: nginx
      state: latest
  - name: enable and start the nginx service
    service: 
        name: nginx 
        enabled: yes
        state: restarted
            
