--- # Lookup playbook example
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
  - debug: msg="Loopup the Superhero for Bruce Wayne {{ lookup('csvfile, 'Wayne file=lookup.csv delimeter=, col=3 default=NOMATCH') }} "


