--- # Web Playbook for Apache web
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars_files:
  - vars/vars.yml
  tasks: 
  - include: packages/pacakges.yml
  - include: commands/commands.yml
  handlers: 
  - include: handler/handler.yml
   




