--- # My first play book on yml
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files: 
   -  copywright.yml
   -  webdefaults.yml
  vars_prompt: 
   - name: pkg_name
     prompt: Which package would you like to install ? 
#when ever defining the action section it could have any modules that can relate to the specific commands
  tasks:
   - name: Install Lynx web browser
     action: yum name=lynx state=installed
   - name:  Installs the Tomcat Web browser
     action: yum name={{ pkg_name }} state=installed
   - name: Checking for telnet clients
     action: yum name=telnet state=latest

