--- # Installing Alfresco on localmachine 
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  - tasks:
       name: Installing the Alfresco52 with Ansible
       


