--- # Installing alfresco from unzipping the file and copying it
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks: 
  - name: Installing the webserver specific version
 


-- copy the necessary files to one    
-- webserver
-- ansible
-- start the server
-- either with unzipping the file from the tar ball file
-- unzip the alfresco
-- copy to the tomact install directory
-- before this check the instance of the working directory
-- run the sql command which creates the database
-- Modify and edit the shared.loader in the catalina.properties file property
-- install the mysql work to execute the task
-- copy the mysql connector to the lib directory
-- so far this is the process 

