--- # Error handling 
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo 
  connection: ssh
  gather_facts: no
  tasks: 
   - name: Execute a command Which will fail
     command: /bin/false
     ignore_errors: yes
   - name: Install emacs
     yum: pkg=emacs state=latest
   
