--- # Playbook on debug Yaml for Debug status in the product. 
- hosts: local
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing the bluefish package on centos
    yum: 
      name: bluefish
      state: latest
    register: result
  - debug: var=result
         
