--- # Stepping at the top 
- hosts: local
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks: 
  - name: Installing Code
    yum: pkg=code state=latest
  - name: Installing Emacs
    yum: pkg=emacs state=latest
  - name: Bypassing Few changes
    command: ls -al > /opt/
    register: result


